### ISSUE TITLE
Assert need_backprop.detach()==1 and tgt_need_backprop.detach()==0

### ISSUE THREAD

**Issue by SkeletonOne** [He-Zhenwei/ATF#1]
In my custom datset:

before filtering, there are 1000 images...
after filtering, there are 1000 images...
source 5000 target 1000 roidb entries
Loading pretrained weights from ./data/pretrained_model/resnet101_caffe.pth
Traceback (most recent call last):
  File "da_trainval_net.py", line 394, in <module>
    tgt_im_data, tgt_im_info, tgt_gt_boxes, tgt_num_boxes, tgt_need_backprop)
  File "/home/skt1/anaconda3/envs/python27atf/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/skt1/content/ATF/lib/model/da_faster_rcnn/faster_rcnn.py", line 112, in forward
    assert need_backprop.detach()==1 and tgt_need_backprop.detach()==0
AssertionError

When I print the need_backprop.detach(), it shows need_backprop.detach()==0, how to solve this problem?

**Comment by leomessi17** [comment]
Change the expression "if im_name.find('source_') == -1:  # target domain"in file "lib/roi_da_data_layer/minibatch.py" according to your special flag of source domain image names.

**Comment by SkeletonOne** [comment]
@leomessi17 Thx, I'll try it!
